const PRODUCT_KEY = "rfs_products";
const ORDER_KEY = "rfs_orders";
const CUSTOMER_KEY = "rfs_customers";
const COUPON_KEY = "rfs_coupons";
const SETTINGS_KEY = "rfs_settings";
const SESSION_KEY = "rfs_admin_session";
const qs = (s, r = document) => r.querySelector(s);
const qsa = (s, r = document) => Array.from(r.querySelectorAll(s));
const money = new Intl.NumberFormat("en-IN", { style: "currency", currency: "INR", maximumFractionDigits: 0 });
const uid = () => (crypto.randomUUID ? crypto.randomUUID() : "id" + Date.now());
const read = (k, v) => { try { return JSON.parse(localStorage.getItem(k) || JSON.stringify(v)); } catch { return v; } };
const write = (k, v) => localStorage.setItem(k, JSON.stringify(v));
const defaultProducts = [
  { id: "alphonso-mango", name: "Alphonso Mango", hi: "Alphonso Mango", category: "mangoes", price: 249, mrp: 329, discount: 24, stock: 42, image: "assets/images/mango.svg", status: "Active", badge: "Best seller", tags: ["featured", "best", "new"], desc: "Naturally sweet Ratnagiri Alphonso mangoes." },
  { id: "kashmir-apple", name: "Kashmir Apple", hi: "Kashmir Apple", category: "apples", price: 179, mrp: 220, discount: 19, stock: 56, image: "assets/images/apple.svg", status: "Active", badge: "Fresh", tags: ["featured", "best"], desc: "Crisp mountain apples." }
];
const defaults = { products: defaultProducts, orders: [], customers: [], coupons: [], settings: { shopName: "Rudra Fruit Shop", logo: "", deliveryCharge: 30, contactNumber: "+91 98765 43210" } };
let state = loadState();
let editingProductId = null;
let editingCouponId = null;
function loadState() { const products = read(PRODUCT_KEY, defaults.products); if (!localStorage.getItem(PRODUCT_KEY)) write(PRODUCT_KEY, products); return { products, orders: read(ORDER_KEY, []), customers: read(CUSTOMER_KEY, []), coupons: read(COUPON_KEY, []), settings: { ...defaults.settings, ...read(SETTINGS_KEY, defaults.settings) } }; }
function persist() { write(PRODUCT_KEY, state.products); write(ORDER_KEY, state.orders); write(CUSTOMER_KEY, state.customers); write(COUPON_KEY, state.coupons); write(SETTINGS_KEY, state.settings); }
function refresh() { state = loadState(); }
function escapeHtml(value) { return String(value ?? "").replace(/[&<>"]/g, ch => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;" }[ch])); }
function escapeAttr(value) { return escapeHtml(value).replace(/'/g, "&#39;"); }
function fileToDataUrl(file) { return new Promise(resolve => { if (!file) return resolve(""); const reader = new FileReader(); reader.onload = () => resolve(reader.result); reader.readAsDataURL(file); }); }
function setMode() { const el = qs("#modeText"); if (el) el.textContent = "LocalStorage mode"; }
function showApp(loggedIn) { qs("#loginView").classList.toggle("hidden", loggedIn); qs("#appView").classList.toggle("hidden", !loggedIn); if (loggedIn) { setMode(); refresh(); renderAll(); } }
qs("#loginForm").addEventListener("submit", e => { e.preventDefault(); const data = Object.fromEntries(new FormData(e.currentTarget)); if (data.email === "admin@rudrafruitshop.com" && data.password === "admin123") { localStorage.setItem(SESSION_KEY, "true"); showApp(true); } else qs("#loginHint").textContent = "Use admin@rudrafruitshop.com / admin123"; });
qs("#logoutBtn").onclick = () => { localStorage.removeItem(SESSION_KEY); showApp(false); };
qs("#themeBtn").onclick = () => { document.body.classList.toggle("dark"); localStorage.setItem("rfs_admin_theme", document.body.classList.contains("dark") ? "dark" : "light"); };
qsa(".sidebar nav button").forEach(button => { button.onclick = () => { qsa(".sidebar nav button").forEach(item => item.classList.remove("active")); qsa(".tab").forEach(tab => tab.classList.remove("active")); button.classList.add("active"); qs("#" + button.dataset.tab).classList.add("active"); qs("#pageTitle").textContent = button.textContent; refresh(); renderAll(); }; });
function totalRevenue() { return state.orders.reduce((sum, order) => sum + Number(order.total || 0), 0); }
function renderAll() { renderDashboard(); renderProducts(); renderOrders(); renderCustomers(); renderInventory(); renderCoupons(); renderReports(); renderSettings(); }
function renderDashboard() { const revenue = totalRevenue(); qs("#dashboard").innerHTML = '<div class="stats"><article class="stat"><span>Total Products</span><strong>' + state.products.length + '</strong></article><article class="stat"><span>Total Orders</span><strong>' + state.orders.length + '</strong></article><article class="stat"><span>Revenue</span><strong>' + money.format(revenue) + '</strong></article><article class="stat"><span>Customers</span><strong>' + state.customers.length + '</strong></article></div><div class="grid"><section class="panel"><h2>Recent Orders</h2><div class="list">' + (state.orders.slice(0, 6).map(o => '<article><div><b>' + o.id + '</b><p>' + (o.name || 'Customer') + '</p></div><span class="badge">' + (o.status || 'Pending') + '</span></article>').join('') || '<p class="empty">No orders yet.</p>') + '</div></section><section class="panel"><h2>Low Stock Alerts</h2><div class="list">' + (state.products.filter(p => Number(p.stock || 0) <= 10).map(p => '<article><div><b>' + p.name + '</b><p>' + p.stock + ' left</p></div><span class="badge warning-text">Low Stock</span></article>').join('') || '<p class="empty">No low stock products.</p>') + '</div></section></div>'; }
function productRows(list) { return list.map(p => '<tr><td>' + (p.image ? '<img class="thumb" src="' + p.image + '" alt="">' : '<div class="thumb"></div>') + '</td><td><b>' + escapeHtml(p.name) + '</b><br><span class="badge">' + (p.status || 'Active') + '</span></td><td>' + escapeHtml(p.category) + '</td><td>' + money.format(p.price || 0) + '<br><small>MRP ' + money.format(p.mrp || p.price || 0) + '</small></td><td>' + Number(p.stock || 0) + '</td><td>' + Number(p.discount || 0) + '%</td><td><div class="row-actions"><button class="ghost" data-edit="' + p.id + '">Edit</button><button class="danger" data-delete="' + p.id + '">Delete</button></div></td></tr>').join(''); }
function renderProducts(filter = "") { const list = state.products.filter(p => String(p.name || '').toLowerCase().includes(filter.toLowerCase()) || String(p.category || '').toLowerCase().includes(filter.toLowerCase())); qs("#products").innerHTML = '<div class="grid"><section class="panel"><h2>' + (editingProductId ? 'Edit Product' : 'Add Product') + '</h2><form id="productForm" class="form-grid"><label>Name<input name="name" required></label><label>Hindi Name<input name="hi"></label><label>Category<select name="category"><option value="mangoes">Mangoes</option><option value="apples">Apples</option><option value="citrus">Citrus</option><option value="berries">Berries</option><option value="tropical">Tropical</option><option value="dry-fruits">Dry Fruits</option></select></label><label>Status<select name="status"><option>Active</option><option>Draft</option><option>Out of Stock</option></select></label><label>Price<input name="price" type="number" min="0" required></label><label>MRP<input name="mrp" type="number" min="0" required></label><label>Discount %<input name="discount" type="number" min="0" max="99" required></label><label>Stock<input name="stock" type="number" min="0" required></label><label>Badge<input name="badge" placeholder="Best seller"></label><label>Tags<input name="tags" placeholder="featured,best,new"></label><label class="wide">Description<textarea name="desc"></textarea></label><label class="wide">Upload Image<input name="image" type="file" accept="image/*"></label><button class="wide" type="submit">' + (editingProductId ? 'Update Product' : 'Add Product') + '</button><button class="wide ghost" type="button" id="resetProduct">Clear Form</button></form></section><section class="panel"><div class="toolbar"><h2>Products</h2><input id="productSearch" placeholder="Search products"></div><div class="table-wrap"><table class="table"><thead><tr><th>Image</th><th>Name</th><th>Category</th><th>Price</th><th>Stock</th><th>Discount</th><th>Actions</th></tr></thead><tbody>' + (productRows(list) || '<tr><td colspan="7" class="empty">No products found.</td></tr>') + '</tbody></table></div></section></div>'; const form = qs("#productForm"); if (editingProductId) fillProductForm(form, state.products.find(p => p.id === editingProductId)); form.onsubmit = saveProduct; qs("#resetProduct").onclick = () => { editingProductId = null; renderProducts(); }; qs("#productSearch").oninput = e => renderProducts(e.target.value); qsa("[data-edit]").forEach(b => b.onclick = () => { editingProductId = b.dataset.edit; renderProducts(); }); qsa("[data-delete]").forEach(b => b.onclick = () => { state.products = state.products.filter(p => p.id !== b.dataset.delete); persist(); renderAll(); }); }
function fillProductForm(form, p) { if (!p) return; form.name.value = p.name || ""; form.hi.value = p.hi || p.name || ""; form.category.value = p.category || "mangoes"; form.status.value = p.status || "Active"; form.price.value = p.price || 0; form.mrp.value = p.mrp || p.price || 0; form.discount.value = p.discount || 0; form.stock.value = p.stock || 0; form.badge.value = p.badge || "Fresh"; form.tags.value = Array.isArray(p.tags) ? p.tags.join(",") : "featured"; form.desc.value = p.desc || ""; }
async function saveProduct(e) { e.preventDefault(); const form = e.currentTarget; const data = Object.fromEntries(new FormData(form)); const existing = state.products.find(p => p.id === editingProductId); const image = await fileToDataUrl(form.image.files[0]); const id = existing?.id || uid(); const product = { id, name: data.name, hi: data.hi || data.name, category: data.category, status: data.status, price: Number(data.price), mrp: Number(data.mrp), discount: Number(data.discount), stock: Number(data.stock), badge: data.badge || "Fresh", tags: String(data.tags || "featured").split(",").map(t => t.trim()).filter(Boolean), desc: data.desc || "", image: image || existing?.image || "assets/images/hero-fruits.svg", updatedAt: new Date().toISOString() }; state.products = existing ? state.products.map(p => p.id === id ? product : p) : [product, ...state.products]; editingProductId = null; persist(); renderAll(); }
function renderOrders() { qs("#orders").innerHTML = '<section class="panel"><h2>View Orders</h2><div class="table-wrap"><table class="table"><thead><tr><th>Order</th><th>Customer</th><th>Total</th><th>Date</th><th>Status</th></tr></thead><tbody>' + (state.orders.map(o => '<tr><td><b>' + o.id + '</b><br><small>' + (o.items || []).map(i => (i.qty || 1) + ' x ' + (i.name || i.id)).join(', ') + '</small></td><td>' + (o.name || 'Customer') + '<br><small>' + (o.phone || '') + '</small></td><td>' + money.format(o.total || 0) + '</td><td>' + (o.date || '') + '</td><td><select data-order="' + o.id + '"><option' + selected(o.status, 'Pending') + '>Pending</option><option' + selected(o.status, 'Packed') + '>Packed</option><option' + selected(o.status, 'Shipped') + '>Shipped</option><option' + selected(o.status, 'Delivered') + '>Delivered</option><option' + selected(o.status, 'Cancelled') + '>Cancelled</option></select></td></tr>').join('') || '<tr><td colspan="5" class="empty">No orders yet.</td></tr>') + '</tbody></table></div></section>'; qsa("[data-order]").forEach(s => s.onchange = () => { const order = state.orders.find(o => o.id === s.dataset.order); if (order) order.status = s.value; persist(); renderDashboard(); }); }
function selected(v, o) { return (v || 'Pending') === o ? ' selected' : ''; }
function renderCustomers() { qs("#customers").innerHTML = '<section class="panel"><h2>Customer List</h2><div class="table-wrap"><table class="table"><thead><tr><th>Name</th><th>Email</th><th>Phone</th><th>Orders</th><th>Total Spent</th><th>Last Order</th></tr></thead><tbody>' + (state.customers.map(c => '<tr><td><b>' + (c.name || 'Customer') + '</b></td><td>' + (c.email || '') + '</td><td>' + (c.phone || '') + '</td><td>' + (c.orders || 0) + '</td><td>' + money.format(c.totalSpent || 0) + '</td><td>' + (c.lastOrderId || '') + '</td></tr>').join('') || '<tr><td colspan="6" class="empty">No customers yet.</td></tr>') + '</tbody></table></div></section>'; }
function renderInventory() { qs("#inventory").innerHTML = '<section class="panel"><h2>Inventory and Low Stock Alerts</h2><div class="table-wrap"><table class="table"><thead><tr><th>Product</th><th>Stock</th><th>Price</th><th>Discount</th><th>Status</th></tr></thead><tbody>' + (state.products.map(p => '<tr><td><b>' + p.name + '</b></td><td><input data-stock="' + p.id + '" type="number" value="' + Number(p.stock || 0) + '"></td><td><input data-price="' + p.id + '" type="number" value="' + Number(p.price || 0) + '"></td><td><input data-discount="' + p.id + '" type="number" value="' + Number(p.discount || 0) + '"></td><td><span class="badge">' + (Number(p.stock || 0) <= 10 ? 'Low Stock' : (p.status || 'Active')) + '</span></td></tr>').join('') || '<tr><td colspan="5" class="empty">No products found.</td></tr>') + '</tbody></table></div></section>'; qsa("[data-stock],[data-price],[data-discount]").forEach(input => input.onchange = () => { const id = input.dataset.stock || input.dataset.price || input.dataset.discount; const p = state.products.find(item => item.id === id); if (!p) return; if (input.dataset.stock) p.stock = Number(input.value); if (input.dataset.price) p.price = Number(input.value); if (input.dataset.discount) p.discount = Number(input.value); persist(); renderDashboard(); }); }
function renderCoupons() { qs("#coupons").innerHTML = '<div class="grid"><section class="panel"><h2>' + (editingCouponId ? 'Edit Coupon' : 'Create Coupon') + '</h2><form id="couponForm" class="form-grid"><label>Coupon Code<input name="code" required></label><label>Discount %<input name="discount" type="number" min="0" max="99" required></label><label>Minimum Order<input name="minOrder" type="number" value="0"></label><label>Status<select name="active"><option value="true">Active</option><option value="false">Inactive</option></select></label><button class="wide">Save Coupon</button><button class="wide ghost" type="button" id="resetCoupon">Clear Form</button></form></section><section class="panel"><h2>Coupons</h2><div class="list">' + (state.coupons.map(c => '<article><div><b>' + c.code + '</b><p>' + c.discount + '% off - Min ' + money.format(c.minOrder || 0) + '</p></div><div class="row-actions"><button class="ghost" data-edit-coupon="' + c.id + '">Edit</button><button class="danger" data-delete-coupon="' + c.id + '">Delete</button></div></article>').join('') || '<p class="empty">No coupons yet.</p>') + '</div></section></div>'; const form = qs("#couponForm"); const edit = state.coupons.find(c => c.id === editingCouponId); if (edit) { form.code.value = edit.code; form.discount.value = edit.discount; form.minOrder.value = edit.minOrder || 0; form.active.value = String(!!edit.active); } form.onsubmit = e => { e.preventDefault(); const d = Object.fromEntries(new FormData(e.currentTarget)); const coupon = { id: edit?.id || uid(), code: d.code.toUpperCase(), discount: Number(d.discount), minOrder: Number(d.minOrder || 0), active: d.active === 'true', updatedAt: new Date().toISOString() }; state.coupons = edit ? state.coupons.map(c => c.id === coupon.id ? coupon : c) : [coupon, ...state.coupons]; editingCouponId = null; persist(); renderCoupons(); }; qs("#resetCoupon").onclick = () => { editingCouponId = null; renderCoupons(); }; qsa("[data-edit-coupon]").forEach(b => b.onclick = () => { editingCouponId = b.dataset.editCoupon; renderCoupons(); }); qsa("[data-delete-coupon]").forEach(b => b.onclick = () => { state.coupons = state.coupons.filter(c => c.id !== b.dataset.deleteCoupon); persist(); renderCoupons(); }); }
function renderReports() { const revenue = totalRevenue(), avg = state.orders.length ? revenue / state.orders.length : 0, delivered = state.orders.filter(o => o.status === 'Delivered').length; qs("#reports").innerHTML = '<div class="stats"><article class="stat"><span>Sales Summary</span><strong>' + money.format(revenue) + '</strong></article><article class="stat"><span>Average Order</span><strong>' + money.format(avg) + '</strong></article><article class="stat"><span>Delivered</span><strong>' + delivered + '</strong></article><article class="stat"><span>Low Stock</span><strong>' + state.products.filter(p => Number(p.stock || 0) <= 10).length + '</strong></article></div><section class="panel"><h2>Sales Summary</h2><div class="mini-chart">' + chartBars() + '</div></section>'; }
function chartBars() { const recent = state.orders.slice(0, 8); if (!recent.length) return [35, 62, 48, 80, 56, 92].map(h => '<span style="height:' + h + '%"></span>').join(''); const max = Math.max(...recent.map(o => Number(o.total || 0)), 1); return recent.map(o => '<span title="' + money.format(o.total || 0) + '" style="height:' + Math.max(18, Number(o.total || 0) / max * 100) + '%"></span>').join(''); }
function renderSettings() { qs("#settings").innerHTML = '<section class="panel"><h2>Store Settings</h2><form id="settingsForm" class="settings-grid"><label>Store Name<input name="shopName" value="' + escapeAttr(state.settings.shopName || '') + '"></label><label>Contact Number<input name="contactNumber" value="' + escapeAttr(state.settings.contactNumber || '') + '"></label><label>Delivery Charge<input name="deliveryCharge" type="number" value="' + Number(state.settings.deliveryCharge || 0) + '"></label><label>Logo Upload<input name="logoFile" type="file" accept="image/*"></label><label class="wide">Logo URL or saved image<input name="logo" value="' + escapeAttr(state.settings.logo || '') + '"></label><button>Save Settings</button></form></section>'; qs("#settingsForm").onsubmit = async e => { e.preventDefault(); const form = e.currentTarget; const data = Object.fromEntries(new FormData(form)); const uploaded = await fileToDataUrl(form.logoFile.files[0]); state.settings = { shopName: data.shopName || 'Rudra Fruit Shop', contactNumber: data.contactNumber || '', deliveryCharge: Number(data.deliveryCharge || 0), logo: uploaded || data.logo || '', updatedAt: new Date().toISOString() }; persist(); renderSettings(); }; }
window.addEventListener('storage', e => { if ([PRODUCT_KEY, ORDER_KEY, CUSTOMER_KEY, COUPON_KEY, SETTINGS_KEY].includes(e.key)) { refresh(); renderAll(); } });
if (localStorage.getItem("rfs_admin_theme") === "dark") document.body.classList.add("dark");
qs("#loginHint").textContent = "Local login: admin@rudrafruitshop.com / admin123";
showApp(localStorage.getItem(SESSION_KEY) === "true");
